package util;

public enum FName {
    LINE, ACTION15MIN, ACTION1MIN, ACTION24H, ACTION, ACTIONUPDATE, BEARTYPE,
    RECORDTIME, ITEM_ID, COUNT, PROVINCEITEM, ITEMTYPE, KEY, RETIME, PROVINCE_ID,
    ORDERTYPE, BOOK_ID, BOOK_PRO, COM, PVPERMIN, SUB, FEE, TOTAL,
    MSISDN, ORDERTIME, CHAPTER_ID, PLATFORM, PRODUCT_ID, REALINFORFEE,
    TIME, STARTTIME, PORTALIP, RESULTCODE, SCENETYPE, ACCESSTYPE, CITY_ID,
    WAPIP, REMOTEIP, PAGENAME, ERRCODE, RECORDTIMELEN, PROCITY, PROCITYITEM,
    TICKETID, UANAME, TERMINAL
}
